// <auto-generated />
using System;
using KataQuestionnaireDynamic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KataQuestionnaireDynamic.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20230731130509_dbNewDb")]
    partial class dbNewDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KataQuestionnaireDynamic.Models.FormularModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("KataQuestionnaireDynamic.Models.OptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionModelId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("KataQuestionnaireDynamic.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionModelId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionModelId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("KataQuestionnaireDynamic.Models.OptionModel", b =>
                {
                    b.HasOne("KataQuestionnaireDynamic.Models.QuestionModel", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionModelId");
                });

            modelBuilder.Entity("KataQuestionnaireDynamic.Models.QuestionModel", b =>
                {
                    b.HasOne("KataQuestionnaireDynamic.Models.FormularModel", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuestionModelId");
                });

            modelBuilder.Entity("KataQuestionnaireDynamic.Models.FormularModel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("KataQuestionnaireDynamic.Models.QuestionModel", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
